app:
  nome: app
server:
  port: 8000
  servlet:
    context-path: /app
  compression:
    enabled: true
spring:
  profiles:
    active: '@activatedProperties@'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: false
backend:
  service:
    url: /api
  
joinfaces:
  ## joinfaces.faces-servlet
  # Configures the FacesServlet handled by JoinFaces.
  faces-servlet:
    async-supported: true
    enabled: true # If the FacesServlet should be actively handled by Joinfaces.
    load-on-startup: -1
    name: FacesServlet
    order: 0 # The order-property for the ServletRegistrationBean.
    url-mappings: '*.jsf,*.faces,*.xhtml'
  jsf:
    state-saving-method: server
    project-stage: production
    facelets-libraries: /taglib/primefaces-ultima.taglib.xml
  primefaces:
    theme: vela
    font-awesome: true

# ================================
# MONITORING CONFIG
# ================================
management:
  endpoint:
    beans:
      cache:
        time-to-live: 10s
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      base-path: /actuator
      cors:
        allowed-methods: GET,POST
        allowed-origins: '*'
      exposure:
        include: '*'
  server:
    port: ${server.port}


# ================================
# LOG LEVEL
# ================================
logging:
  #  pattern:
  #    console: '%d{HH:mm:ss.SSS} [app=${app.nome}] [%t] %-5level %logger{36} - %msg%n'
  level:
    root: INFO
    br.com.gfsolucoesti: DEBUG



