server:
  port: 8000
backend:
  service:
    url: http://localhost:8000/api
joinfaces:
  ## joinfaces.faces-servlet
  # Configures the FacesServlet handled by JoinFaces.
  faces-servlet:
    async-supported: true
    enabled: true # If the FacesServlet should be actively handled by Joinfaces.
    load-on-startup: -1
    name: FacesServlet
    order: 0 # The order-property for the ServletRegistrationBean.
    url-mappings: /faces/*,*.jsf,*.faces,*.xhtml
  jsf:
    PROJECT_STAGE: Production
  primefaces:
    theme: saga


